import * as Icons from 'griddy-icons';
import { PlayFilled, PauseFilled } from '../components/CustomIcons';

/**
 * Griddy Icons Registry
 * Exports a subset of icons used in the application for centralized management
 */
export const griddyRegistry = {
  Activity: Icons.Activity,
  Steps: Icons.Steps,
  Barbell: Icons.Barbell,
  Bike: Icons.Bike,
  Heart: Icons.BloodDrop,
  Calendar: Icons.Calendar,
  Chart: Icons.ChartLineSmooth,
  Chat: Icons.ChatBubbleText,
  Check: Icons.Check,
  Clock: Icons.Alarm,
  Fire: Icons.Fire,
  Map: Icons.Map,
  Profile: Icons.AddressBook,
  Settings: Icons.Apps,
  Star: Icons.Badge,
  Alert: Icons.AlertTriangle,
  Info: Icons.AnnotationInfo,
  Bug: Icons.Bug,
  ArrowRight: Icons.ArrowRight,
  ChevronRight: Icons.ChevronRight,
  ArrowLeft: Icons.ArrowLeft,
  User: Icons.User,
  Image: Icons.Image,
  Moon: Icons.Moon,
  Translate: Icons.Translate,
  Download: Icons.ArrowDown,
  Volume: Icons.VolumeMax,
  Shield: Icons.ShieldCheck,
  Timer: Icons.Alarm,
  MapPin: Icons.LocationPin,
  Dumbbell: Icons.Barbell,
  Refresh: Icons.RefreshCw,
  ArrowDown: Icons.ArrowDown,
  Wind: Icons.Wind,
  WifiOff: Icons.BluetoothOff,
  Message: Icons.ChatBubble,
  X: Icons.Close,
  History: Icons.TimeUpdate,
  HistoryGrid: Icons.Apps,
  Repetisi: Icons.Switch,
  HardDrive: Icons.Package,
  ExternalLink: Icons.ArrowUpRight,
  Save: Icons.Archive,
  Trash: Icons.Trash,
  ChevronDown: Icons.ChevronDown,
  ChevronUp: Icons.ChevronUp,
  Eye: Icons.Eye,
  Copy: Icons.Clipboard,
  PlusCircle: Icons.PlusCircle,
  Search: Icons.Search,
  Send: Icons.Send,
  More: Icons.Apps,
  Menu: Icons.AlignTextJustifyLeft,
  Share: Icons.ShareAndroid,
  Camera: Icons.PhotoCamera,
  Edit: Icons.AnnotationText,
  Lock: Icons.Lock,
  LogOut: Icons.LogOut,
  Cpu: Icons.Monitor,
  Brain: Icons.Activity,
  Cloud: Icons.Cloud,
  Database: Icons.Database,
  Loader: Icons.RefreshCw,
  Badge: Icons.Badge,
  Gauge: Icons.ChartLineSmooth,
  Mountain: Icons.WaterWaveBig,
  Target: Icons.ChartLineSmooth,
  ShieldCheck: Icons.ShieldCheck,
  HeartPulse: Icons.BloodDrop,
  Code: Icons.Bug,
  Copyright: Icons.AnnotationInfo,
  Mail: Icons.ChatBubbleText,
  FileCode: Icons.FileCode,
  Calculator: Icons.Calculator,
  TrendingDown: Icons.ChartLineDown,
  ShieldAlert: Icons.ShieldAlert,
  Pause: PauseFilled,
  Play: PlayFilled,
  Maximize: Icons.Maximize,
  Minimize: Icons.Minimize,
  Signal: Icons.CellTower,
  Flame: Icons.Fire,
  Filter: Icons.AlignTextJustifyLeft,
  Upload: Icons.ArrowUp,
  CheckCircle: Icons.CheckCircle,
  Tally: Icons.AnnotationText,
  Lunges: Icons.Activity,
  BeerAlt: Icons.BeerAlt,
  Square: Icons.Archive,
  TrendingUp: Icons.ChartLineSmooth,
  Unlock: Icons.LockOpen,
  Locate: Icons.LocationMy,
  Plus: Icons.Plus,
  Minus: Icons.Minus,
  Scale: Icons.ChartLineSmooth,
  BarChart: Icons.ChartBar,
  Ruler: Icons.AlignTextJustifyLeft,
  Trend: Icons.TrendUp,
  Zap: Icons.Flash,
};

export type IconName = keyof typeof griddyRegistry;

export default griddyRegistry;
